# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wsdb}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-02-28}
  s.description = %q{Used to authenticate and track web service usage}
  s.email = %q{tom@jackhq.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/db/migrate/001_create_accounts.rb",
     "lib/db/migrate/002_create_domains.rb",
     "lib/db/migrate/003_create_posts.rb",
     "lib/mixins/timestamps.rb",
     "lib/models/account.rb",
     "lib/models/domain.rb",
     "lib/models/post.rb",
     "lib/wsdb.rb"
  ]
  s.homepage = %q{http://github.com/twilson63/wsdb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Web Service Usage Database}
  s.test_files = [
    "spec/models/account_spec.rb",
     "spec/models/domain_spec.rb",
     "spec/models/post_spec.rb",
     "spec/spec_helper.rb",
     "spec/wsdb_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 0.3.8"])
      s.add_runtime_dependency(%q<validatable>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sequel>, [">= 0.3.8"])
      s.add_dependency(%q<validatable>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 0.3.8"])
    s.add_dependency(%q<validatable>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

